
   
/**   
const myArray = [
    {
    age : "10"
    },
    {
    age : "20"
    },
    {
    age : "21"
    },
    {
    age : "22"
    }
];

function filterStudents(students, cb){
    const newArray = [];
    for(let student of students){   // filter defined on the next line dynamically generated by a call back function
        if(cb(student)){
            newArray.push(student);
        }
    }
    return newArray;
}

console.log(                            //console log funtion with filter
  filterStudents(myArray, (student)=>{
      return student.age >=10;
  })  
);
**/
const STUDENTS = [
    {
    age : "10"
    },
    {
    age : "20"
    },
    {
    age : "21"
    },
    {
    age : "22"
    }
];

function filterStudentsByAge(students, age){
    const newArray = [];
    for(let student of students){   // loop through each student object
        if(student.age >= 10){      // define filter
            newArray.push(student);
        }
    }
    return newArray;
}

console.log(filterStudentsByAge(STUDENTS, 10));